; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=LA32 %s
; RUN: llc --mtriple=loongarch64 --verify-machineinstrs < %s \
; RUN:   | FileCheck --check-prefix=LA64 %s

;; Verify that we lower @llvm.trap() and @llvm.debugtrap() correctly.

declare void @llvm.trap()
declare void @llvm.debugtrap()

define void @test_trap() nounwind {
; LA32-LABEL: test_trap:
; LA32:       # %bb.0:
; LA32-NEXT:    break 0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_trap:
; LA64:       # %bb.0:
; LA64-NEXT:    break 0
; LA64-NEXT:    ret
  tail call void @llvm.trap()
  ret void
}

define void @test_debugtrap() nounwind {
; LA32-LABEL: test_debugtrap:
; LA32:       # %bb.0:
; LA32-NEXT:    break 0
; LA32-NEXT:    ret
;
; LA64-LABEL: test_debugtrap:
; LA64:       # %bb.0:
; LA64-NEXT:    break 0
; LA64-NEXT:    ret
  tail call void @llvm.debugtrap()
  ret void
}
